### ISSUE TITLE
create_env.py script doesn't work on Windows

### ISSUE THREAD

**Issue by Winand** [LinkedInLearning/testing-python-data-science-code-2477020#1]
## Issue Overview
`create_env.py` looks for python executable in `.venv/bin` folder, but it is inside `.venv/Scripts`

## Describe your environment
Windows 10, pyenv-win

## Possible Solution
Check if `.venv/Scripts` exists

**Comment by tebeka** [comment]
Thanks for reporting! I'll have a look and update.
